### ISSUE TITLE
There is no CMakeLists.txt.. how to build with cmake?  

### ISSUE THREAD

**Issue by walnut-engineering** [AlamyLiu/ftdi_prog#1]
There is no CMakeLists.txt.. how to build with cmake?  

~/ftdi_prog$ cmake -DCMAKE_INSTALL_PREFIX="/usr/local" ../
CMake Error: The source directory "/home/tradr" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

Thanks

**Comment by AlamyLiu** [comment]
Sorry for the confusion.  That's to build libftdi from source, and install it under /usr/local/
`libftdi 1.4 Installed under /usr/local $ cmake -DCMAKE_INSTALL_PREFIX="/usr/local" ../`

To build ftdi_prog, it's just `make`
